services:
  postgres:
    image: "postgres:latest"
    container_name: "postgres_db"
    restart: "always"
    environment:
      - "POSTGRES_DB=majestor_db"
      - "POSTGRES_PASSWORD=admin"
      - "POSTGRES_USER=abdullah"
    ports:
      - "5432:5432"
