security:
  jwt:
    secret-key: ${JWT_SECRET_KEY}

aws:
  s3:
    buckets:
      bucket: ${S3_BUCKET_NAME}

  region: ${S3_BUCKET_REGION}

spring:
  application:
    name: api

  datasource:
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    url: ${DATABASE_URL}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      hibernate:
        format_sql: true

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SUPPORT_EMAIL}
    password: ${APP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true

  config:
    import: optional:file:.env[.properties]

  profiles:
    active: DEV

#logging:
#  level:
#    root: ERROR
#    org.springframework.web: DEBUG
#    org.hibernate: DEBUG
