CREATE TABLE bookings
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    ride_id             BIGINT                                  NOT NULL,
    booked_ride_request BIGINT                                  NOT NULL,
    deviation_km        DECIMAL                                 NOT NULL,
    status              VARCHAR(255)                            NOT NULL,
    created_at          TIMESTAMP WITHOUT TIME ZONE,
    updated_at          TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_bookings PRIMARY KEY (id)
);

CREATE TABLE courses
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    faculty_id BIGINT                                  NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE document_images
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    image_uri      VARCHAR(255)                            NOT NULL,
    file_extension VARCHAR(255)                            NOT NULL,
    serial_number  BIGINT                                  NOT NULL,
    document_id    BIGINT                                  NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_document_images PRIMARY KEY (id)
);

CREATE TABLE documents
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title           VARCHAR(255)                            NOT NULL,
    uploaded_year   BIGINT                                  NOT NULL,
    document_type   VARCHAR(255)                            NOT NULL,
    semester_type   VARCHAR(255)                            NOT NULL,
    destination     VARCHAR(255)                            NOT NULL,
    is_premium_only BOOLEAN                                 NOT NULL,
    total_file_size BIGINT                                  NOT NULL,
    uploader_id     BIGINT                                  NOT NULL,
    course_id       BIGINT,
    study_group_id  BIGINT,
    created_at      TIMESTAMP WITHOUT TIME ZONE,
    updated_at      TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_documents PRIMARY KEY (id)
);

CREATE TABLE faculties
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255),
    university_id BIGINT                                  NOT NULL,
    created_at    TIMESTAMP WITHOUT TIME ZONE,
    updated_at    TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_faculties PRIMARY KEY (id)
);

CREATE TABLE fare_configs
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    vehicle_type VARCHAR(255)                            NOT NULL,
    price_per_km INTEGER                                 NOT NULL,
    CONSTRAINT pk_fare_configs PRIMARY KEY (id)
);

CREATE TABLE likes
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id     BIGINT                                  NOT NULL,
    document_id BIGINT                                  NOT NULL,
    CONSTRAINT pk_likes PRIMARY KEY (id)
);

CREATE TABLE notifications
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    title             VARCHAR(255),
    message           VARCHAR(255),
    related_id        BIGINT,
    sender_id         BIGINT,
    recipient_id      BIGINT                                  NOT NULL,
    notification_type VARCHAR(255),
    is_read           BOOLEAN                                 NOT NULL,
    response          VARCHAR(255),
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_notifications PRIMARY KEY (id)
);

CREATE TABLE ratings
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    rated_by          BIGINT,
    rated_study_group BIGINT,
    created_at        TIMESTAMP WITHOUT TIME ZONE,
    updated_at        TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ratings PRIMARY KEY (id)
);

CREATE TABLE ride_requests
(
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    pickup_location_lat      DECIMAL(10, 7)                          NOT NULL,
    pickup_location_lng      DECIMAL(10, 7)                          NOT NULL,
    pickup_location_address  VARCHAR(255)                            NOT NULL,
    dropoff_location_lat     DECIMAL(10, 7)                          NOT NULL,
    dropoff_location_lng     DECIMAL(10, 7)                          NOT NULL,
    dropoff_location_address VARCHAR(255)                            NOT NULL,
    number_of_passengers     INTEGER                                 NOT NULL,
    phone                    VARCHAR(255)                            NOT NULL,
    route_distance_km        DECIMAL                                 NOT NULL,
    ride_request_status      VARCHAR(255)                            NOT NULL,
    ride_requester_id        BIGINT                                  NOT NULL,
    created_at               TIMESTAMP WITHOUT TIME ZONE,
    updated_at               TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_ride_requests PRIMARY KEY (id)
);

CREATE TABLE rides
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_location_lat     DECIMAL(10, 7)                          NOT NULL,
    start_location_lng     DECIMAL(10, 7)                          NOT NULL,
    start_location_address VARCHAR(255)                            NOT NULL,
    end_location_lat       DECIMAL(10, 7)                          NOT NULL,
    end_location_lng       DECIMAL(10, 7)                          NOT NULL,
    end_location_address   VARCHAR(255)                            NOT NULL,
    vehicle_modal          VARCHAR(255)                            NOT NULL,
    license_plate          VARCHAR(255)                            NOT NULL,
    available_seats        INTEGER                                 NOT NULL,
    vehicle_type           VARCHAR(255)                            NOT NULL,
    ride_status            VARCHAR(255),
    phone                  VARCHAR(255)                            NOT NULL,
    route_distance_km      DECIMAL                                 NOT NULL,
    ride_poster_id         BIGINT                                  NOT NULL,
    created_at             TIMESTAMP WITHOUT TIME ZONE,
    updated_at             TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_rides PRIMARY KEY (id)
);

CREATE TABLE study_group_invites
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    status         VARCHAR(255),
    study_group_id BIGINT                                  NOT NULL,
    inviter_id     BIGINT                                  NOT NULL,
    invitee_id     BIGINT                                  NOT NULL,
    created_at     TIMESTAMP WITHOUT TIME ZONE,
    updated_at     TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_study_group_invites PRIMARY KEY (id)
);

CREATE TABLE study_group_members
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    study_group_id  BIGINT                                  NOT NULL,
    group_member_id BIGINT                                  NOT NULL,
    joined_at       TIMESTAMP WITHOUT TIME ZONE,
    left_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_study_group_members PRIMARY KEY (id)
);

CREATE TABLE study_groups
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name               VARCHAR(255)                            NOT NULL,
    is_official        BOOLEAN                                 NOT NULL,
    is_active          BOOLEAN                                 NOT NULL,
    popularity_score   DOUBLE PRECISION                        NOT NULL,
    is_private         BOOLEAN                                 NOT NULL,
    study_group_host   BIGINT,
    study_group_course BIGINT,
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_study_groups PRIMARY KEY (id)
);

CREATE TABLE universities
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(100),
    address    VARCHAR(255),
    created_at TIMESTAMP WITHOUT TIME ZONE,
    updated_at TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_universities PRIMARY KEY (id)
);

CREATE TABLE university_domains
(
    university_id BIGINT NOT NULL,
    domain        VARCHAR(255)
);

CREATE TABLE user_roles
(
    user_id BIGINT NOT NULL,
    role    VARCHAR(255)
);

CREATE TABLE users
(
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    email              VARCHAR(255)                            NOT NULL,
    username           VARCHAR(20)                             NOT NULL,
    password_hash      VARCHAR(255)                            NOT NULL,
    phone              VARCHAR(255),
    personal_email     VARCHAR(255),
    avatar             VARCHAR(255),
    has_onboarded      BOOLEAN,
    is_faculty         BOOLEAN                                 NOT NULL,
    premium_until      TIMESTAMP WITHOUT TIME ZONE,
    storage_used       BIGINT                                  NOT NULL,
    storage_limit      BIGINT                                  NOT NULL,
    expo_push_token    VARCHAR(255),
    university_id      BIGINT                                  NOT NULL,
    faculty_id         BIGINT                                  NOT NULL,
    verification_token VARCHAR(255),
    is_verified        BOOLEAN                                 NOT NULL,
    reset_token        VARCHAR(255),
    created_at         TIMESTAMP WITHOUT TIME ZONE,
    updated_at         TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE documents
    ADD CONSTRAINT uc_documents_title UNIQUE (title);

ALTER TABLE fare_configs
    ADD CONSTRAINT uc_fare_configs_vehicletype UNIQUE (vehicle_type);

ALTER TABLE study_groups
    ADD CONSTRAINT uc_study_groups_name UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_username UNIQUE (username);

CREATE INDEX idx_user_email ON users (email);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_BOOKED_RIDE_REQUEST FOREIGN KEY (booked_ride_request) REFERENCES ride_requests (id);

ALTER TABLE bookings
    ADD CONSTRAINT FK_BOOKINGS_ON_RIDE FOREIGN KEY (ride_id) REFERENCES rides (id);

ALTER TABLE courses
    ADD CONSTRAINT FK_COURSES_ON_FACULTY FOREIGN KEY (faculty_id) REFERENCES faculties (id);

ALTER TABLE documents
    ADD CONSTRAINT FK_DOCUMENTS_ON_COURSE FOREIGN KEY (course_id) REFERENCES courses (id);

ALTER TABLE documents
    ADD CONSTRAINT FK_DOCUMENTS_ON_STUDY_GROUP FOREIGN KEY (study_group_id) REFERENCES study_groups (id);

ALTER TABLE documents
    ADD CONSTRAINT FK_DOCUMENTS_ON_UPLOADER FOREIGN KEY (uploader_id) REFERENCES users (id);

CREATE INDEX idx_uploader_id ON documents (uploader_id);

ALTER TABLE document_images
    ADD CONSTRAINT FK_DOCUMENT_IMAGES_ON_DOCUMENT FOREIGN KEY (document_id) REFERENCES documents (id);

CREATE INDEX idx_document_id ON document_images (document_id);

ALTER TABLE faculties
    ADD CONSTRAINT FK_FACULTIES_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES universities (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_DOCUMENT FOREIGN KEY (document_id) REFERENCES documents (id);

ALTER TABLE likes
    ADD CONSTRAINT FK_LIKES_ON_USER FOREIGN KEY (user_id) REFERENCES users (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_RECIPIENT FOREIGN KEY (recipient_id) REFERENCES users (id);

ALTER TABLE notifications
    ADD CONSTRAINT FK_NOTIFICATIONS_ON_SENDER FOREIGN KEY (sender_id) REFERENCES users (id);

ALTER TABLE ratings
    ADD CONSTRAINT FK_RATINGS_ON_RATEDBY FOREIGN KEY (rated_by) REFERENCES users (id);

ALTER TABLE ratings
    ADD CONSTRAINT FK_RATINGS_ON_RATEDSTUDYGROUP FOREIGN KEY (rated_study_group) REFERENCES study_groups (id);

ALTER TABLE rides
    ADD CONSTRAINT FK_RIDES_ON_RIDE_POSTER FOREIGN KEY (ride_poster_id) REFERENCES users (id);

ALTER TABLE ride_requests
    ADD CONSTRAINT FK_RIDE_REQUESTS_ON_RIDE_REQUESTER FOREIGN KEY (ride_requester_id) REFERENCES users (id);

ALTER TABLE study_groups
    ADD CONSTRAINT FK_STUDY_GROUPS_ON_STUDY_GROUP_COURSE FOREIGN KEY (study_group_course) REFERENCES courses (id);

ALTER TABLE study_groups
    ADD CONSTRAINT FK_STUDY_GROUPS_ON_STUDY_GROUP_HOST FOREIGN KEY (study_group_host) REFERENCES users (id);

ALTER TABLE study_group_invites
    ADD CONSTRAINT FK_STUDY_GROUP_INVITES_ON_INVITEE FOREIGN KEY (invitee_id) REFERENCES users (id);

ALTER TABLE study_group_invites
    ADD CONSTRAINT FK_STUDY_GROUP_INVITES_ON_INVITER FOREIGN KEY (inviter_id) REFERENCES users (id);

ALTER TABLE study_group_invites
    ADD CONSTRAINT FK_STUDY_GROUP_INVITES_ON_STUDY_GROUP FOREIGN KEY (study_group_id) REFERENCES study_groups (id);

ALTER TABLE study_group_members
    ADD CONSTRAINT FK_STUDY_GROUP_MEMBERS_ON_GROUP_MEMBER FOREIGN KEY (group_member_id) REFERENCES users (id);

ALTER TABLE study_group_members
    ADD CONSTRAINT FK_STUDY_GROUP_MEMBERS_ON_STUDY_GROUP FOREIGN KEY (study_group_id) REFERENCES study_groups (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_FACULTY FOREIGN KEY (faculty_id) REFERENCES faculties (id);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_UNIVERSITY FOREIGN KEY (university_id) REFERENCES universities (id);

ALTER TABLE university_domains
    ADD CONSTRAINT fk_university_domains_on_university FOREIGN KEY (university_id) REFERENCES universities (id);

ALTER TABLE user_roles
    ADD CONSTRAINT fk_user_roles_on_user FOREIGN KEY (user_id) REFERENCES users (id);